theme: minimal
title: Hello Am MIKE
author: Michael kamau
email: mikeylkamau222@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Am a self taught developer who is still learning and open for 
  opportunities if any. Am also a big fun of tech.

# social links
twitter_username: mikey_razor # DO NOT include the @ character, or else the build will fail!
github_username:  mik284 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
